Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
   config.vm.network "forwarded_port", guest: 80, host: 8888
   config.vm.provision "file", source: "./index.html", destination: "/tmp/index.html"
   config.vm.provision "shell", inline: <<-SHELL
     yum install -y httpd
     mv /tmp/index.html /var/www/html/
     systemctl start httpd
     systemctl enable httpd
   SHELL
end
